# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'kenos1/tmux-cht-sh'

# General
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-interval 10

set -g mouse on
set -g set-clipboard on

set -sg escape-time 20
set -s focus-events on
set-hook -g session-created 'send-keys "clear && fastfetch" C-m'

# Keybindings
set -g prefix C-Space
bind C-Space send-prefix

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind "'" split-window -h -c "#{pane_current_path}"

bind < swap-window -d -t -1
bind > swap-window -d -t +1

bind Enter copy-mode
unbind -T copy-mode Space
bind -T copy-mode Space send -X begin-selection

set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Theme
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "basic"
set -g status-left "#{?session_name,[#S] ,}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g window-status-separator " "

set -g default-terminal "xterm-256color"
set -g status-right-length 100
set -g status-left-length 100

set -g @catppuccin_status_fill "all"
set -g status-right "#(whoami)@#H "
set -g @catppuccin_status_left_separator "█"
set -agF status-right "#{E:@catppuccin_status_application}"
set -g @catppuccin_application_icon ""
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -g @catppuccin_cpu_icon ""
set -agF status-right "#{@catppuccin_status_gitmux}"
set -g @catppuccin_gitmux_icon ""

run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g @sidebar-tree-position 'right'
set -sa terminal-overrides ",xterm*:Tc"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
