# Catppuccin config
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_cpu_icon ""
set -g @catppuccin_directory_icon ""
set -g @catppuccin_gitmux_icon ""

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'kenos1/tmux-cht-sh'
set -g @plugin 'hiroppy/tmux-agent-sidebar'

# General
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-interval 10

set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on

set -sg escape-time 20
set -s focus-events on
set-hook -g session-created 'send-keys "clear && fastfetch" C-m'

set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g default-terminal "xterm-256color"
set -sa terminal-overrides ",xterm*:Tc"
set -g @sidebar_auto_create 'off'

set-window-option -g main-pane-width 70%
set-window-option -g main-pane-height 70%

# Keybindings
set -g prefix C-Space
bind C-Space send-prefix

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind "'" split-window -h -c "#{pane_current_path}"

bind < swap-window -d -t -1
bind > swap-window -d -t +1

bind Enter copy-mode
bind -T copy-mode Space send -X begin-selection

bind C-p display-popup -d "#{pane_current_path}" -E -w 80% -h 40% -y 0 '
	file=$(find -L . \( \
		-path "*/.git" \
		-or -path "*/node_modules" \
		-or -path "*/build" \
		-or -path "*/dist" \
	\) -prune -o -type f -printf "%P\n" 2>/dev/null | fzf --reverse --scheme=path)
	[ -n "$file" ] && tmux new-window "${EDITOR:-micro}" "$file"
'

# Theme
run '~/.tmux/plugins/tmux/catppuccin.tmux'
set -g status-left "#{?session_name,[#S] ,}"
set -g window-status-separator " "
set -g status-right-length 100
set -g status-left-length 100

set -g status-right '#(set -- #{SSH_CONNECTION}; [ -n "$1" ] && echo "$1:$2 > ")'
set -ag status-right "#(whoami)@#H "
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{@catppuccin_status_gitmux}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Override cht-sh size
unbind-key S
bind-key S display-popup -w 80% -h 80% -E "$HOME/.tmux/plugins/tmux-cht-sh/bin/tmux-cht-sh.sh"
